import { getSettings } from "@/lib/settings";
import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { homedir } from "os";
import path from "path";

const PLIST_LABEL = "today.positron.positronitron";
const LAUNCH_AGENTS_DIR = path.join(homedir(), "Library", "LaunchAgents");
const PLIST_PATH = path.join(LAUNCH_AGENTS_DIR, `${PLIST_LABEL}.plist`);
const REPO_PLIST_PATH = path.join(process.cwd(), "..", "scripts", `${PLIST_LABEL}.plist`);
const LOG_PATH = path.join(homedir(), "Library", "Logs", "positron-positronitron.log");

function generatePlist(times: { hour: number; minute: number }[]): string {
  const intervals = times
    .map(
      (t) => `    <dict>
      <key>Hour</key>
      <integer>${t.hour}</integer>
      <key>Minute</key>
      <integer>${t.minute}</integer>
    </dict>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>

  <!-- Auto-generated by Positron admin — do not edit manually -->
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/curl</string>
    <string>-s</string>
    <string>-X</string>
    <string>POST</string>
    <string>http://localhost:3000/api/positronitron</string>
  </array>

  <key>StartCalendarInterval</key>
  <array>
${intervals}
  </array>

  <key>StandardOutPath</key>
  <string>${LOG_PATH}</string>
  <key>StandardErrorPath</key>
  <string>${LOG_PATH}</string>
</dict>
</plist>
`;
}

export async function POST() {
  try {
    const settings = await getSettings();
    let times: string[];
    try {
      times = JSON.parse(settings.positronitron_run_times);
    } catch {
      return Response.json({ error: "Invalid run times format" }, { status: 400 });
    }

    if (!Array.isArray(times) || times.length < 1 || times.length > 4) {
      return Response.json({ error: "Need 1-4 run times" }, { status: 400 });
    }

    const parsed = times.map((t) => {
      const m = String(t).match(/^(\d{1,2}):(\d{2})$/);
      if (!m) throw new Error(`Invalid time format: ${t}`);
      const hour = parseInt(m[1], 10);
      const minute = parseInt(m[2], 10);
      if (hour < 0 || hour > 23 || minute < 0 || minute > 59) {
        throw new Error(`Time out of range: ${t}`);
      }
      return { hour, minute };
    });

    const plistXml = generatePlist(parsed);

    // Unload existing job (ignore error if not loaded)
    try {
      execSync(`launchctl unload "${PLIST_PATH}" 2>/dev/null`, { timeout: 5000 });
    } catch {
      // Not currently loaded — that's fine
    }

    // Write to both LaunchAgents and repo
    writeFileSync(PLIST_PATH, plistXml, "utf-8");
    writeFileSync(REPO_PLIST_PATH, plistXml, "utf-8");

    // Load the updated job
    execSync(`launchctl load "${PLIST_PATH}"`, { timeout: 5000 });

    return Response.json({ ok: true, times: times });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return Response.json({ error: message }, { status: 500 });
  }
}
